import pandas as pd
import numpy as np

def build_normal_baseline(features_df, anomalous_ids):
    
    print("Building baseline from normal users")
    normal_df = features_df.drop(anomalous_ids, errors='ignore')
    baseline = {
        "mean": normal_df.mean().to_dict(), 
        "std": normal_df.std().to_dict()
    }
    return baseline

def generate_visual_report(user_id, anomaly_metrics, baseline):

    print("\n" + "="*70)
    print(f"  EXPLANATION REPORT FOR ANOMALOUS USER: {user_id}")
    print("="*70)
    print(f"{'Metric':<30} | {'Anomalous Value':<20} | {'Normal Avg (± Std)':<25}")
    print("-" * 80)
    
    summary_points = []
    
    # Mapping raw feature names to user-friendly labels 
    metric_name_map = {
        'out_degree': 'Transactions Sent (Count)',
        'in_degree': 'Transactions Received (Count)',
        'total_amount_sent': 'Total Amount Sent ($)',
        'total_amount_received': 'Total Amount Received ($)'
    }

    for key, label in metric_name_map.items():
        anom_val = anomaly_metrics[key]
        mean = baseline['mean'][key]
        std = baseline['std'][key]
        
        if "amount" in key:
            norm_str = f"${mean:,.2f} (± ${std:,.2f})"
            anom_str = f"${anom_val:,.2f}"
        else:
            norm_str = f"{mean:,.1f} (± {std:,.1f})"
            anom_str = f"{int(anom_val):,}"

        print(f"{label:<30} | {anom_str:<20} | {norm_str:<25}")

        if std > 0:
            z_score = (anom_val - mean) / std
            if abs(z_score) > 3:
                direction = "higher" if z_score > 0 else "lower"
                summary_points.append(f">> {label} is extremely {direction} than normal ({z_score:.1f} std. deviations).")

    print("\nExplanation Summary")
    if not summary_points:
        print("This user's metrics do not show simple deviations, but their combination was flagged as rare")
    else:
        for point in summary_points:
            print(point)
    print("="*70)

if __name__ == "__main__":
    print("Loading detected anomalies and feature data")
    try:
        # Load data generated by detector.py
        features_df = pd.read_csv('features_data.csv', index_col='user_id')
        anomalies_df = pd.read_csv('detected_anomalies.csv')
        detected_anomalies = anomalies_df['anomalous_user_id'].tolist()
    except FileNotFoundError:
        print("Error: Required data files not found. Run detector.py first.")
        exit()

    baseline = build_normal_baseline(features_df, detected_anomalies)
    
    print(f"\nGenerating Reports for {len(detected_anomalies)} Anomalies")
    csv_data = []
    
    for user_id in detected_anomalies:
        try:
            anomaly_metrics = features_df.loc[user_id].to_dict()
            
            generate_visual_report(user_id, anomaly_metrics, baseline)
            
            row = {'user_id': user_id}
            for key in ['out_degree', 'in_degree', 'total_amount_sent', 'total_amount_received']:
                mean = baseline['mean'][key]
                std = baseline['std'][key]
                val = anomaly_metrics[key]
                z_score = (val - mean) / std if std > 0 else 0
                
                row[f'{key} (Value)'] = val
                row[f'{key} (Normal Avg)'] = mean
                row[f'{key} (Normal Std)'] = std  
                row[f'{key} (Z-Score)'] = z_score

            csv_data.append(row)
        except Exception as e:
            print(f"Error processing user {user_id}: {e}")

    final_csv = pd.DataFrame(csv_data)
    final_csv.to_csv("anomaly_report.csv", index=False)
    print("\nProject Complete. Final evidence exported to 'anomaly_report.csv'")
